name: add new users
on:
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install ODBC Driver for SQL Server
      run: |
        sudo apt-get update
        sudo apt-get install -y unixodbc-dev
        sudo apt-get install -y msodbcsql18
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sqlalchemy pyodbc tenacity
    
    - name: Run addUsersFromCSV script
      env:
        AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }}
        AZURE_SQL_DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
        AZURE_SQL_USERNAME: ${{ secrets.AZURE_SQL_USERNAME }}
        AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
      run: python addUsersFromCSV.py
   
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
